<?php

return [

    'field_types' => [
        \Statamic\Fieldtypes\Arr::class,
        \Statamic\Fieldtypes\Assets\Assets::class,
        \Statamic\Fieldtypes\Bard::class,
        \Statamic\Fieldtypes\ButtonGroup::class,
        \Statamic\Fieldtypes\Checkboxes::class,
        \Statamic\Fieldtypes\Code::class,
        \Statamic\Fieldtypes\Collections::class,
        \Statamic\Fieldtypes\Color::class,
        \Statamic\Fieldtypes\Date::class,
        \Statamic\Fieldtypes\Entries::class,
        // TODO: \Statamic\Fieldtypes\Form::class,
        \Statamic\Fieldtypes\Grid::class,
        \Statamic\Fieldtypes\Hidden::class,
        \Statamic\Fieldtypes\Html::class,
        \Statamic\Fieldtypes\Integer::class,
        \Statamic\Fieldtypes\Link::class,
        \Statamic\Fieldtypes\Lists::class,
        \Statamic\Fieldtypes\Markdown::class,
        \Statamic\Fieldtypes\Radio::class,
        \Statamic\Fieldtypes\Range::class,
        \Statamic\Fieldtypes\Replicator::class,
        \Statamic\Fieldtypes\Revealer::class,
        \Statamic\Fieldtypes\Section::class,
        \Statamic\Fieldtypes\Select::class,
        \Statamic\Fieldtypes\Sites::class,
        \Statamic\Fieldtypes\Slug::class,
        \Statamic\Fieldtypes\Structures::class,
        \Statamic\Fieldtypes\Table::class,
        // TODO: \Statamic\Fieldtypes\Tags::class,
        \Statamic\Fieldtypes\Taxonomies::class,
        \Statamic\Fieldtypes\Template::class,
        \Statamic\Fieldtypes\Terms::class,
        \Statamic\Fieldtypes\Text::class,
        \Statamic\Fieldtypes\Textarea::class,
        \Statamic\Fieldtypes\Time::class,
        \Statamic\Fieldtypes\Toggle::class,
        \Statamic\Fieldtypes\UserGroups::class,
        \Statamic\Fieldtypes\UserRoles::class,
        \Statamic\Fieldtypes\Users::class,
        \Statamic\Fieldtypes\Video::class,
        \Statamic\Fieldtypes\Yaml::class,
    ],

];
